#!/usr/local/bin/node

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const {JSDOM } = jsdom;

request(url, function(error, response, body) {
  //Simulate a Document Object Model
  let { document } = (new JSDOM(body)).window;

  // Grab all the paragraphs and references.
  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference");

  // Remove all references
  references.forEach(function(reference) {
    reference.remove();
  });

  // Print out paragraphs
  paragraphs.forEach(function(paragraph) {
    console.log(paragraph.textContent);
  });
});
